export const metadata = { title: 'Terms of Service — Dropiq' };

export default function TermsPage() {
  return (
    <div className="px-8 py-10 max-w-3xl">
      <h1 className="text-2xl font-semibold text-white mb-2">Terms of Service</h1>
      <p className="text-slate-500 text-sm mb-10">Last updated: June 2026</p>

      <div className="space-y-8 text-sm text-slate-300 leading-relaxed">
        <section>
          <h2 className="text-base font-semibold text-white mb-3">1. Acceptance</h2>
          <p>By creating an account and using Dropiq, you agree to these Terms of Service. If you do not agree, do not use the service.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-white mb-3">2. The service</h2>
          <p>Dropiq provides AI-generated content tools including product analysis, copy generation, ad script creation, and competitor research. All content is generated by AI and provided for informational and creative purposes. You are responsible for reviewing and using any generated content appropriately.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-white mb-3">3. Your account</h2>
          <ul className="space-y-2 list-disc list-inside text-slate-400">
            <li>You must be 18 or older to use Dropiq</li>
            <li>You are responsible for keeping your account credentials secure</li>
            <li>One account per person — sharing accounts is not permitted</li>
            <li>You may not use Dropiq for illegal purposes or to generate content that violates applicable laws</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-semibold text-white mb-3">4. Plans and billing</h2>
          <ul className="space-y-2 list-disc list-inside text-slate-400">
            <li>Subscriptions are billed monthly and renew automatically</li>
            <li>You can cancel at any time — cancellation takes effect at the end of the current billing period</li>
            <li>Generation limits reset on the 1st of each calendar month</li>
            <li>We reserve the right to change pricing with 30 days notice</li>
            <li>No refunds for partial months</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-semibold text-white mb-3">5. Content and intellectual property</h2>
          <p>AI-generated content produced using Dropiq is yours to use commercially. You own the inputs you provide and the outputs you generate. We do not claim ownership over your generated content.</p>
          <p className="mt-2">You are responsible for ensuring your use of generated content does not infringe third-party intellectual property rights, including trademarks and copyrights.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-white mb-3">6. Acceptable use</h2>
          <p className="mb-2">You agree not to:</p>
          <ul className="space-y-2 list-disc list-inside text-slate-400">
            <li>Attempt to reverse engineer, scrape, or abuse the API</li>
            <li>Use automated bots to generate content at scale beyond your plan limits</li>
            <li>Resell access to Dropiq without prior written agreement (Agency plan includes white-label rights)</li>
            <li>Generate content intended to deceive, defraud, or harm consumers</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-semibold text-white mb-3">7. Disclaimer</h2>
          <p>AI-generated content is provided as-is. Dropiq does not guarantee the accuracy, legality, or commercial success of any generated content. Product verdicts and market analysis are AI opinions, not financial or legal advice.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-white mb-3">8. Limitation of liability</h2>
          <p>Dropiq is not liable for any indirect, incidental, or consequential damages arising from your use of the service, including lost profits, ad spend, or business decisions made based on AI-generated content.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-white mb-3">9. Termination</h2>
          <p>We reserve the right to suspend or terminate accounts that violate these terms, at our discretion and without prior notice in cases of serious violations.</p>
        </section>

        <section>
          <h2 className="text-base font-semibold text-white mb-3">10. Contact</h2>
          <p>Questions about these terms: <a href="mailto:support@dropiq.io" className="text-violet-400 hover:text-violet-300">support@dropiq.io</a></p>
        </section>
      </div>
    </div>
  );
}
